-- Create Expense Table
CREATE TABLE
  expense (
    id UUID PRIMARY KEY, -- Assuming you use UUIDs for IDs
    amount NUMERIC(15, 2) NOT NULL, -- NUMERIC for precise financial values
    date DATE NOT NULL
  );

CREATE TABLE
  public."role" (
    id INT GENERATED BY DEFAULT AS IDENTITY (
      INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE
    ),
    "role" VARCHAR(64) NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id)
  );

-- Create Staff Table
CREATE TABLE
  public.staff (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    "position" VARCHAR(50),
    contact_number VARCHAR(15),
    email VARCHAR(100) UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "role" INT,
    CONSTRAINT staff_role_fk FOREIGN KEY ("role") REFERENCES public."role" (id) DEFERRABLE INITIALLY DEFERRED
  );

-- Create Index on role column in Staff Table
CREATE INDEX staff_role_idx ON public.staff USING btree ("role");

INSERT INTO
  public."role" (id, "role")
VALUES
  (483647, 'admin');

INSERT INTO
  public."role" (id, "role")
VALUES
  (483547, 'employee');

INSERT INTO
  public.staff (
    first_name,
    last_name,
    "position",
    contact_number,
    email,
    "password",
    "role"
  )
VALUES
  (
    'megan',
    'johnson',
    'admin',
    '0112223333',
    'megan.johnson@email.com',
    '$2a$10$Os5ZK05XWylSAVLYECAWVuCSykoA0cIlmMRWAZzCYaceFY0gBUTUq',
    483647
  );